# Messageは誰かがTNTを設置した場合にサーバー全体に青色で表示されるチャットです。なお、設置した人の名前は必ず一番最初に表示されます。
Message: "さんがTNTを設置したため削除しました。"
# Mesage2は爆発寸前のTNTを削除するときにサーバー全体に表示されるチャットです。なお、これは着火した人などは表示されません。
Message2: "爆発寸前のTNTを削除しました。"